[package]
name = "typecheck-ts"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
ahash = "0.8"
derive-visitor = "0.4.0"
parse-js = { path = "../../parse-js" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
symbol-js = { path = "../../symbol-js" }

[[bench]]
name = "pipeline"
harness = false
