force_explicit_abi = true
hard_tabs = false
newline_style = "Unix"
merge_derives = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = true
