[package]
name = "minify-js-bench"
publish = false
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
diagnostics = { workspace = true }
minify-js = { workspace = true }
