[package]
name = "webidl-vm-js"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vm-js = { workspace = true }
webidl = { workspace = true }

