[package]
name = "semantic-js-w8"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
diagnostics-w8 = { path = "../diagnostics-w8" }
hir-js-w8 = { path = "../hir-js-w8" }
rustc-hash = "1.1.0"
