[package]
name = "hir-js-w106"
version = "0.1.0"
edition = "2021"

[features]
fuzzing = []

[dependencies]
derive-visitor = "0.4.0"
parse-js = { path = "../parse-js" }
symbol-js = { path = "../symbol-js" }
thiserror = "1"

[dev-dependencies]
proptest = "1"
