[package]
name = "typecheck-ts-w13"
version = "0.1.0"
edition = "2021"

[dependencies]
parse-js = { path = "../parse-js" }
bumpalo = { version = "3.15.4", features = ["collections"] }

[dev-dependencies]
once_cell = "1.19.0"
