[package]
name = "vm-js"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
diagnostics = { workspace = true }
thiserror = { workspace = true }
