[package]
name = "diagnostics"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde"]
[dev-dependencies]
serde_json = "1"
