[package]
name = "semantic-js-w111"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]

[dependencies]
serde = { version = "1.0.216", features = ["derive"], optional = true }

[dev-dependencies]
rmp-serde = "1.3.0"
serde_json = "1.0.133"
