[package]
name = "runtime-js"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
diagnostics = { workspace = true }
parse-js = { workspace = true, features = ["diagnostics"] }
vm-js = { workspace = true }
