[package]
name = "test262"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
diagnostics = { path = "../diagnostics" }
parse-js = { path = "../parse-js", features = ["diagnostics"] }
rayon = "1.6"
